using System.Text.Json;
using Brusca.Core.Enums;

namespace Brusca.Core.Models.Cleaning;

/// <summary>
/// A Cleaning run — one invocation pointed at a root path.
/// Every scan, analysis, rename and reorganization operation is scoped here.
/// </summary>
public sealed class Cleaning
{
    public Guid Id { get; init; } = Guid.NewGuid();
    public string RootPath { get; set; } = string.Empty;
    public CleaningStatus Status { get; set; } = CleaningStatus.Pending;
    public DateTime CreatedAtUtc { get; init; } = DateTime.UtcNow;
    public DateTime? CompletedAtUtc { get; set; }
    public string CreatedByUserId { get; set; } = string.Empty;
    public string? Notes { get; set; }

    // ── Restart support ──────────────────────────────────────────────────────
    /// <summary>
    /// Number of times this Cleaning has been restarted from scratch.
    /// Incremented by RestartAsync. Used for audit traceability.
    /// </summary>
    public int RestartCount { get; set; }
    public DateTime? LastRestartedAtUtc { get; set; }

    // ── Archive support ──────────────────────────────────────────────────────
    /// <summary>
    /// Set when the Cleaning has been moved out of the working tables into
    /// the archive tables. Only one un-archived (active) Cleaning may exist
    /// at any time.
    /// </summary>
    public DateTime? ArchivedAtUtc { get; set; }

    // ── Execution target ─────────────────────────────────────────────────────
    /// <summary>
    /// Chosen by the user before execution.
    /// SourcePath = original RootPath (requires double-confirmation).
    /// AlternatePath = a safe staging copy.
    /// </summary>
    public ExecutionTarget ExecutionTarget { get; set; } = ExecutionTarget.SourcePath;

    /// <summary>
    /// Populated when ExecutionTarget == AlternatePath.
    /// All file operations are performed here instead of RootPath.
    /// </summary>
    public string? AlternateExecutionPath { get; set; }

    // ── Snapshots ────────────────────────────────────────────────────────────
    /// <summary>JSON snapshot of the directory tree captured at scan time (before state).</summary>
    public string? BeforeTreeJson { get; set; }

    /// <summary>
    /// JSON snapshot of the projected directory tree after all approved steps
    /// are applied. Computed from BeforeTreeJson + approved PromptStepCommands.
    /// </summary>
    public string? AfterTreeJson { get; set; }

    // ── Relations ────────────────────────────────────────────────────────────
    public IReadOnlyList<CleaningFileExtension> FileExtensions { get; set; } = [];
    public IReadOnlyList<CleaningPromptStep> PromptSteps { get; set; } = [];
}

/// <summary>A file extension discovered during a specific Cleaning scan.</summary>
public sealed class CleaningFileExtension
{
    public Guid Id { get; init; } = Guid.NewGuid();
    public Guid CleaningId { get; set; }
    public Guid ExtensionId { get; set; }
    public string Extension { get; set; } = string.Empty;
    public int FileCount { get; set; }
    public FileExtensionStatus Status { get; set; }
    public string? SuggestedNuGetPackage { get; set; }
    public DateTime DiscoveredAtUtc { get; init; } = DateTime.UtcNow;
}

/// <summary>
/// A single ordered prompt step generated by Claude for a Cleaning run.
/// Each step has a stable GUID and carries one or more executable commands.
/// Steps are stored in sequence and executed in that order.
/// </summary>
public sealed class CleaningPromptStep
{
    /// <summary>Stable GUID for this prompt step — persists across restarts.</summary>
    public Guid Id { get; init; } = Guid.NewGuid();
    public Guid CleaningId { get; set; }
    public int StepOrder { get; set; }
    public PromptStepType StepType { get; set; }

    /// <summary>The human-readable rationale / description Claude generated.</summary>
    public string PromptText { get; set; } = string.Empty;
    public string? GeneratedResponse { get; set; }
    public string? SourcePath { get; set; }
    public string? ProposedTargetPath { get; set; }
    public bool IsApproved { get; set; }
    public bool IsExecuted { get; set; }
    public DateTime CreatedAtUtc { get; init; } = DateTime.UtcNow;
    public DateTime? ExecutedAtUtc { get; set; }
    public string? ExecutionError { get; set; }

    /// <summary>
    /// The executable commands for this step — one per language (C#, CMD, PowerShell).
    /// Each command has its own GUID for fine-grained audit and replay.
    /// </summary>
    public IReadOnlyList<PromptStepCommand> Commands { get; set; } = [];
}

/// <summary>
/// A concrete executable command that implements a PromptStep.
/// Multiple commands per step allow the executor to pick the appropriate
/// language for the host environment (C#, CMD, PowerShell).
///
/// Each command carries its own GUID for audit, replay, and independent
/// error tracking. Commands are stored in prompts.PromptStepCommand.
/// </summary>
public sealed class PromptStepCommand
{
    /// <summary>Stable GUID — unique per command, independent of StepId.</summary>
    public Guid Id { get; init; } = Guid.NewGuid();

    /// <summary>The parent prompt step.</summary>
    public Guid PromptStepId { get; set; }

    /// <summary>Which language this command is written in.</summary>
    public CommandLanguage Language { get; set; }

    /// <summary>
    /// The full, runnable command body.
    /// For C#: a complete snippet using File/Directory APIs.
    /// For CMD: a batch command (e.g. RENAME, MOVE, MKDIR, XCOPY).
    /// For PowerShell: a complete PS1 snippet (Rename-Item, Move-Item, etc.).
    /// </summary>
    public string CommandBody { get; set; } = string.Empty;

    /// <summary>Display order within the step (lowest runs first).</summary>
    public int CommandOrder { get; set; }

    public bool IsExecuted { get; set; }
    public DateTime? ExecutedAtUtc { get; set; }
    public string? ExecutionError { get; set; }
    public DateTime CreatedAtUtc { get; init; } = DateTime.UtcNow;
}

/// <summary>Directory tree node — used for before/after snapshots.</summary>
public sealed class DirectoryNode
{
    public string FullPath { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public int Depth { get; set; }
    public int FileCount { get; set; }
    public List<string> Extensions { get; set; } = [];
    public List<DirectoryNode> Children { get; set; } = [];
    public List<string> Files { get; set; } = [];
}

/// <summary>
/// The before/after tree pair returned by the API for the comparison view.
/// </summary>
public sealed class TreeComparisonResult
{
    public Guid CleaningId { get; set; }
    public DirectoryNode? BeforeTree { get; set; }
    public DirectoryNode? AfterTree { get; set; }
    public int TotalRenames { get; set; }
    public int TotalMoves { get; set; }
    public bool IsAfterProjected { get; set; }
}
